create:
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://admin:Gmo%40%23123@101.99.14.221:108/CreateCopied?authSource=admin"
  MONGODB_HOST:
  MONGODB_PORT:
  MONGODB_USER:
  MONGODB_PASSWORD:
  MONGODB_DATABASE: CreateCopied

  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: data_lake
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  POSTGRES_HOST: 14.225.205.7
  POSTGRES_PORT: 5432
