runcockpit:
  outputs:
    dev:
      dbname: runcokpit
      host: 10.6.201.222
      pass: password
      port: 3000
      schema: warehouse_data
      threads: 1
      type: postgres
      user: postgres
  target: dev
